version: '3.8'

services:
  mysql:
    build: ./docker/mysql
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: optcgsim_api_development
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    platform: linux/amd64
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DB_HOST: mysql
      DB_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: optcgsim_api_development
    volumes:
      - .:/app
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data:
