default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['MYSQL_USER'] || 'root' %>
  password: <%= ENV['MYSQL_PASSWORD'] || 'password' %>
  host: <%= ENV['DB_HOST'] || 'mysql' %>
  port: <%= ENV['DB_PORT'] || 3306 %>

development:
  <<: *default
  database: optcgsim_api_development

test:
  <<: *default
  database: optcgsim_api_test

production:
  <<: *default
  database: optcgsim_api_production
